# Generated by Django 4.2.27 on 2025-12-21 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, help_text='Unique order reference for customer communication', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (Cart)'), ('pending', 'Pending Payment'), ('paid', 'Paid'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup/Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('total_minor', models.PositiveIntegerField(default=0, help_text='Order total in minor units (kobo)')),
                ('delivery_address', models.TextField(blank=True, help_text='Delivery address provided at checkout')),
                ('delivery_instructions', models.TextField(blank=True, help_text='Special instructions for delivery')),
                ('paystack_reference', models.CharField(blank=True, db_index=True, help_text='Paystack transaction reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was confirmed', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_minor', models.PositiveIntegerField(help_text='Price per unit at time of order (snapshot)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'unique_together': {('order', 'menu_item')},
            },
        ),
    ]
