# Generated by Django 4.2.27 on 2025-12-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(db_index=True, help_text='WhatsApp ID from Meta API (usually phone number)', max_length=50, unique=True)),
                ('phone_number', models.CharField(help_text='Phone number for display and payment purposes', max_length=20)),
                ('name', models.CharField(blank=True, help_text="User's name from WhatsApp profile or conversation", max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Email for Paystack transactions', max_length=254)),
                ('default_address', models.TextField(blank=True, help_text='Saved delivery address for quick checkout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
