# Generated by Django 4.2.27 on 2025-12-21 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(default='start', help_text='Current conversation state', max_length=50)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Temporary context data for current state')),
                ('last_message_id', models.CharField(blank=True, db_index=True, help_text='Last processed message ID for idempotency', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_order', models.ForeignKey(blank=True, help_text='Active cart/order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_session', to='orders.order')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Conversation Session',
                'verbose_name_plural': 'Conversation Sessions',
            },
        ),
    ]
